id: P009546
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20219
  title: དཔལ་རྡོ་རྗེ་སེམས་དཔའི་ཐུགས་ཀྱི་སྒྲུབ་པའཻ་བསྙེན་ཡིག་མདོར་དྲིལ་བ་ཡེ་ཤེས་རང་གསལ།
  author: ''
  volumes:
    abd8d01a3d3248569535a497df2bd893:
      image_group_id: I8LS20221
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
