id: I66C6ACBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:38:21+00:00'
last_modified: '2022-06-08T11:47:54.154906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20219
  title: དཔལ་རྡོ་རྗེ་སེམས་དཔའི་ཐུགས་ཀྱི་སྒྲུབ་པའཻ་བསྙེན་ཡིག་མདོར་དྲིལ་བ་ཡེ་ཤེས་རང་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    873E:
      image_group_id: I8LS20221
      title: ''
      total_pages: 56
      order: 1
      base_file: 873E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
